[project]
name = "dify-zep-plugin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dify-plugin>=0.4.0",
    "packaging>=24.2",
    "ruff>=0.11.0",
    "zep-cloud>=2.7.0",
]
